---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - dependencies
    schedule:
      interval: "weekly"
    groups:
      patches:
        patterns:
          - "*"
        update-types:
          - patch
      minors:
        patterns:
          - "*"
        update-types:
          - minor
  - package-ecosystem: "npm"
    directory: "/"
    labels:
      - dependencies
    schedule:
      interval: "weekly"
    versioning-strategy: increase
    groups:
      patches:
        patterns:
          - "*"
        update-types:
          - patch
      minors:
        patterns:
          - "*"
        update-types:
          - minor
